version: "3"  
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      http.cors.enabled: "true"
      http.cors.allow-origin: "*"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on: ['elasticsearch']
    ports:
      - 5601:5601

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.6.2
    ports:
      - 7200:7200
    user: apm-server
    volumes:
      - ./config/apm-server.yml:/usr/share/apm-server/apm-server.yml
    command: /usr/share/apm-server/apm-server -e -c /usr/share/apm-server/apm-server.yml -E apm-server.host=apm-server:7200 --strict.perms=false
    depends_on: ['elasticsearch', 'kibana']